### ISSUE TITLE
可以留个联系方式m q

### ISSUE THREAD

**Issue by liwen7758** [WangJerry1229/XXT_Library_Auto#1]

**Comment by jeremisty99** [comment]
我看原项目说好像接口都加密了吗 我这一段时间也没用过 有啥事吗

**Comment by liwen7758** [comment]
一直没用过了吗？

**Comment by Doone-skser** [comment]
> 我看原项目说好像接口都加密了吗 我这一段时间也没用过 有啥事吗

改的是登录的加密方式，除此之外号登录多了会弹出验证码。

**Comment by dz2353641365** [comment]
> > 我看原项目说好像接口都加密了吗 我这一段时间也没用过 有啥事吗
> 
> 改的是登录的加密方式，除此之外号登录多了会弹出验证码。

怎么搞个？

**Comment by dz2353641365** [comment]
> > 我看原项目说好像接口都加密了吗 我这一段时间也没用过 有啥事吗
> 
> 改的是登录的加密方式，除此之外号登录多了会弹出验证码。

能留个联系方式吗
