### ISSUE TITLE
老版预约接口问题

### ISSUE THREAD

**Issue by zyk494965817** [WangJerry1229/XXT_Library_Auto#2]
自己在写老版的预约接口，发送数据后总是返回{'msg': '预约失败，请退出后重试！', 'success': False}，对比了一下代码感觉没什么区别，想请教一下

**Comment by zyk494965817** [comment]
解决了，应该是url里没有加captcha，

**Comment by MeiXiaoKe1212** [comment]
你好，现在预约要带token和enc参数，这两个在哪里拿到啊？
