### ISSUE TITLE
谢谢您还在维护这个项目。不过好巧，我昨天在改您几年前的版本改成我们学校的了，没想到您更新啦

### ISSUE THREAD

**Issue by everrwsr** [WangJerry1229/XXT_Library_Auto#4]
谢谢

**Comment by jeremisty99** [comment]
也是一时兴起 就继续研究了一会 要是能起到一些帮助就更好了

**Comment by everrwsr** [comment]
很有帮助，免除了我很大一部分工作，就是学习通的验证方式变了让我自己折腾了好久（我自己折腾完了才发现你更新了）最后我依据朋友的需求完成主函数设计，刚刚扔上服务器跑几天看看
