### ISSUE TITLE
请问作者，您一般使用什么工具完成抓包分析呢，enc 这个字段折磨我很久，想要去找点资料学习下，您有推荐的关键字或者课程吗？

### ISSUE THREAD

**Issue by everrwsr** [WangJerry1229/XXT_Library_Auto#6]
我在网上搜索到的一些都比较零散，我看着不太得要领🥹

**Comment by jeremisty99** [comment]
我也没系统学过 抓包电脑端就是fiddler 手机端用的小黄鸟 enc这个基本是完全靠分析js得到的 也是看了之前另外一个issues里的提示用ChatGPT帮助还原了一下

**Comment by everrwsr** [comment]
这样啊，谢谢您啦。我就是那个尝试解密解除到一半解不出来，拿chatgpt简单重命名变量名字的哈哈。我可以问一下您就是那个enc_data的表单设计，您是尝试出来的，还是抓包出来的（如果是抓包出来的，请问你抓取的是哪个url的），我算出来的enc值一直不行。（ps:captcha加上也不对）
![image](https://github.com/WangJerry1229/XXT_Library_Auto/assets/25475909/7e4a4fd6-8069-4ce1-8f69-75734d9492a6)

**Comment by jeremisty99** [comment]
这个我是从js里看的 解密完了之后data的结构就在代码里

**Comment by jeremisty99** [comment]
抓的url就是submit那个 我用的那里边的enc检验算法对不对

**Comment by everrwsr** [comment]
> 抓的url就是submit那个 我用的那里边的enc检验算法对不对

谢谢，我试试

**Comment by everrwsr** [comment]
> 这个我是从js里看的 解密完了之后data的结构就在代码里

这样啊，谢谢，我javascript不太行，所以我使用解密工具https://github.com/Manx98/jsjiami-v6-decryptor ，得到的文件和你的enc.js差别好大，您是不是纯手动解密的啊。总之谢谢您回答我疑问哈哈。得去仔细学下这个了。
```
define(['md5'], function () {
    function _0x2d5317(_0x3dfa7f) {
        var _0x47ea5f = Object.keys(_0x3dfa7f).sort();
        var _0x20d004 = {};
        for (let _0x10bc64 = 0; _0x10bc64 < _0x47ea5f.length; _0x10bc64++) {
            _0x20d004[_0x47ea5f[_0x10bc64]] = _0x3dfa7f[_0x47ea5f[_0x10bc64]];
        }
        return _0x20d004;
    }
    function _0x6d646b(_0x363910) {
        var _0x579e00 = '%sd`~7^/>N4!Q#){\'\'';
        var _0x55d05b = _0x2d5317(_0x363910);
        var _0x3f612d = [];
        for (var _0x4f6a5d in _0x55d05b) {
            _0x3f612d.push('[' + _0x4f6a5d + '=' + _0x55d05b[_0x4f6a5d] + ']');
        }
        _0x3f612d.push('[' + _0x579e00 + ']');
        var _0x485bac = '';
        for (var _0xb5bf84 = 0; _0xb5bf84 < _0x3f612d.length; _0xb5bf84++) {
            _0x485bac += _0x3f612d[_0xb5bf84];
        }
        return hex_md5(_0x485bac);
    }
    return { 'verifyParam': _0x6d646b };
});
(function (_0x266bf7, _0xec214d, _0x432101) {
    var _0x58e0f3 = function () {
        var _0x815ad2 = true;
        return function (_0x3b7d6e, _0x262cdc) {
            var _0x23544f = _0x815ad2 ? function () {
                if (_0x262cdc) {
                    var _0x51827b = _0x262cdc.apply(_0x3b7d6e, arguments);
                    _0x262cdc = null;
                    return _0x51827b;
                }
            } : function () {
            };
            _0x815ad2 = false;
            return _0x23544f;
        };
    }();
    (function () {
        _0x58e0f3(this, function () {
            var _0x415f58 = new RegExp('function *\\( *\\)');
            var _0xcae670 = new RegExp('\\+\\+ *(?:_0x(?:[a-f0-9]){4,6}|(?:\\b|\\d)[a-z0-9]{1,4}(?:\\b|\\d))', 'i');
            var _0x214a1a = _0x2771d2('init');
            if (!_0x415f58.test(_0x214a1a + 'chain') || !_0xcae670.test(_0x214a1a + 'input')) {
                _0x214a1a('0');
            } else {
                _0x2771d2();
            }
        })();
    }());
    var _0x1b0c4d = function () {
        var _0xccfaed = true;
        return function (_0x2ca1cb, _0x3c5b69) {
            var _0x46164b = _0xccfaed ? function () {
                if (_0x3c5b69) {
                    var _0x378433 = _0x3c5b69.apply(_0x2ca1cb, arguments);
                    _0x3c5b69 = null;
                    return _0x378433;
                }
            } : function () {
            };
            _0xccfaed = false;
            return _0x46164b;
        };
    }();
    var _0x3e9443 = _0x1b0c4d(this, function () {
        var _0x6215e8 = function () {
        };
        var _0x8ae592 = typeof window !== 'undefined' ? window : typeof process === 'object' && typeof require === 'function' && typeof global === 'object' ? global : this;
        if (!_0x8ae592.console) {
            _0x8ae592.console = function (_0x2251ea) {
                var _0x432101 = {};
                _0x432101.log = _0x2251ea;
                _0x432101.warn = _0x2251ea;
                _0x432101.debug = _0x2251ea;
                _0x432101.info = _0x2251ea;
                _0x432101.error = _0x2251ea;
                _0x432101.exception = _0x2251ea;
                _0x432101.trace = _0x2251ea;
                return _0x432101;
            }(_0x6215e8);
        } else {
            _0x8ae592.console.log = _0x6215e8;
            _0x8ae592.console.warn = _0x6215e8;
            _0x8ae592.console.debug = _0x6215e8;
            _0x8ae592.console.info = _0x6215e8;
            _0x8ae592.console.error = _0x6215e8;
            _0x8ae592.console.exception = _0x6215e8;
            _0x8ae592.console.trace = _0x6215e8;
        }
    });
    _0x3e9443();
}(window));
function _0x2771d2(_0x5f4b85) {
    function _0x3a0add(_0x4dee5b) {
        {
            if (('' + _0x4dee5b / _0x4dee5b).length !== 1 || _0x4dee5b % 20 === 0) {
                debugger;
            } else {
                debugger;
            }
        }
        _0x3a0add(++_0x4dee5b);
    }
    try {
        if (_0x5f4b85) {
            return _0x3a0add;
        } else {
            _0x3a0add(0);
        }
    } catch (_0x1fbfd5) {
    }
}
setInterval(function () {
    _0x2771d2();
}, 4000);
encode_version = 'jsjiami.com.v5';
```

**Comment by jeremisty99** [comment]
> > 这个我是从js里看的 解密完了之后data的结构就在代码里
> 
> 这样啊，谢谢，我javascript不太行，所以我使用解密工具https://github.com/Manx98/jsjiami-v6-decryptor ，得到的文件和你的enc.js差别好大，您是不是纯手动解密的啊。总之谢谢您回答我疑问哈哈。得去仔细学下这个了。
> 
> ```
> define(['md5'], function () {
>     function _0x2d5317(_0x3dfa7f) {
>         var _0x47ea5f = Object.keys(_0x3dfa7f).sort();
>         var _0x20d004 = {};
>         for (let _0x10bc64 = 0; _0x10bc64 < _0x47ea5f.length; _0x10bc64++) {
>             _0x20d004[_0x47ea5f[_0x10bc64]] = _0x3dfa7f[_0x47ea5f[_0x10bc64]];
>         }
>         return _0x20d004;
>     }
>     function _0x6d646b(_0x363910) {
>         var _0x579e00 = '%sd`~7^/>N4!Q#){\'\'';
>         var _0x55d05b = _0x2d5317(_0x363910);
>         var _0x3f612d = [];
>         for (var _0x4f6a5d in _0x55d05b) {
>             _0x3f612d.push('[' + _0x4f6a5d + '=' + _0x55d05b[_0x4f6a5d] + ']');
>         }
>         _0x3f612d.push('[' + _0x579e00 + ']');
>         var _0x485bac = '';
>         for (var _0xb5bf84 = 0; _0xb5bf84 < _0x3f612d.length; _0xb5bf84++) {
>             _0x485bac += _0x3f612d[_0xb5bf84];
>         }
>         return hex_md5(_0x485bac);
>     }
>     return { 'verifyParam': _0x6d646b };
> });
> (function (_0x266bf7, _0xec214d, _0x432101) {
>     var _0x58e0f3 = function () {
>         var _0x815ad2 = true;
>         return function (_0x3b7d6e, _0x262cdc) {
>             var _0x23544f = _0x815ad2 ? function () {
>                 if (_0x262cdc) {
>                     var _0x51827b = _0x262cdc.apply(_0x3b7d6e, arguments);
>                     _0x262cdc = null;
>                     return _0x51827b;
>                 }
>             } : function () {
>             };
>             _0x815ad2 = false;
>             return _0x23544f;
>         };
>     }();
>     (function () {
>         _0x58e0f3(this, function () {
>             var _0x415f58 = new RegExp('function *\\( *\\)');
>             var _0xcae670 = new RegExp('\\+\\+ *(?:_0x(?:[a-f0-9]){4,6}|(?:\\b|\\d)[a-z0-9]{1,4}(?:\\b|\\d))', 'i');
>             var _0x214a1a = _0x2771d2('init');
>             if (!_0x415f58.test(_0x214a1a + 'chain') || !_0xcae670.test(_0x214a1a + 'input')) {
>                 _0x214a1a('0');
>             } else {
>                 _0x2771d2();
>             }
>         })();
>     }());
>     var _0x1b0c4d = function () {
>         var _0xccfaed = true;
>         return function (_0x2ca1cb, _0x3c5b69) {
>             var _0x46164b = _0xccfaed ? function () {
>                 if (_0x3c5b69) {
>                     var _0x378433 = _0x3c5b69.apply(_0x2ca1cb, arguments);
>                     _0x3c5b69 = null;
>                     return _0x378433;
>                 }
>             } : function () {
>             };
>             _0xccfaed = false;
>             return _0x46164b;
>         };
>     }();
>     var _0x3e9443 = _0x1b0c4d(this, function () {
>         var _0x6215e8 = function () {
>         };
>         var _0x8ae592 = typeof window !== 'undefined' ? window : typeof process === 'object' && typeof require === 'function' && typeof global === 'object' ? global : this;
>         if (!_0x8ae592.console) {
>             _0x8ae592.console = function (_0x2251ea) {
>                 var _0x432101 = {};
>                 _0x432101.log = _0x2251ea;
>                 _0x432101.warn = _0x2251ea;
>                 _0x432101.debug = _0x2251ea;
>                 _0x432101.info = _0x2251ea;
>                 _0x432101.error = _0x2251ea;
>                 _0x432101.exception = _0x2251ea;
>                 _0x432101.trace = _0x2251ea;
>                 return _0x432101;
>             }(_0x6215e8);
>         } else {
>             _0x8ae592.console.log = _0x6215e8;
>             _0x8ae592.console.warn = _0x6215e8;
>             _0x8ae592.console.debug = _0x6215e8;
>             _0x8ae592.console.info = _0x6215e8;
>             _0x8ae592.console.error = _0x6215e8;
>             _0x8ae592.console.exception = _0x6215e8;
>             _0x8ae592.console.trace = _0x6215e8;
>         }
>     });
>     _0x3e9443();
> }(window));
> function _0x2771d2(_0x5f4b85) {
>     function _0x3a0add(_0x4dee5b) {
>         {
>             if (('' + _0x4dee5b / _0x4dee5b).length !== 1 || _0x4dee5b % 20 === 0) {
>                 debugger;
>             } else {
>                 debugger;
>             }
>         }
>         _0x3a0add(++_0x4dee5b);
>     }
>     try {
>         if (_0x5f4b85) {
>             return _0x3a0add;
>         } else {
>             _0x3a0add(0);
>         }
>     } catch (_0x1fbfd5) {
>     }
> }
> setInterval(function () {
>     _0x2771d2();
> }, 4000);
> encode_version = 'jsjiami.com.v5';
> ```

我就是用了你发的这个工具才得到结果的 一开始我找的工具效果差一点 真正有效的就是开头到 return { 'verifyParam': _0x6d646b };这一部分 其实你仔细看一下就发现跟我enc里的那些是完全对应的 我是在ChatGPT还原的基础上改出来的

**Comment by everrwsr** [comment]
感谢，我成了哈哈哈
![image](https://github.com/WangJerry1229/XXT_Library_Auto/assets/25475909/181d545f-98d9-4b12-8742-5161fad3ea75)

**Comment by everrwsr** [comment]
> > > 这个我是从js里看的 解密完了之后data的结构就在代码里
> > 
> > 
> > 这样啊，谢谢，我javascript不太行，所以我使用解密工具https://github.com/Manx98/jsjiami-v6-decryptor ，得到的文件和你的enc.js差别好大，您是不是纯手动解密的啊。总之谢谢您回答我疑问哈哈。得去仔细学下这个了。
> > ```
> > define(['md5'], function () {
> >     function _0x2d5317(_0x3dfa7f) {
> >         var _0x47ea5f = Object.keys(_0x3dfa7f).sort();
> >         var _0x20d004 = {};
> >         for (let _0x10bc64 = 0; _0x10bc64 < _0x47ea5f.length; _0x10bc64++) {
> >             _0x20d004[_0x47ea5f[_0x10bc64]] = _0x3dfa7f[_0x47ea5f[_0x10bc64]];
> >         }
> >         return _0x20d004;
> >     }
> >     function _0x6d646b(_0x363910) {
> >         var _0x579e00 = '%sd`~7^/>N4!Q#){\'\'';
> >         var _0x55d05b = _0x2d5317(_0x363910);
> >         var _0x3f612d = [];
> >         for (var _0x4f6a5d in _0x55d05b) {
> >             _0x3f612d.push('[' + _0x4f6a5d + '=' + _0x55d05b[_0x4f6a5d] + ']');
> >         }
> >         _0x3f612d.push('[' + _0x579e00 + ']');
> >         var _0x485bac = '';
> >         for (var _0xb5bf84 = 0; _0xb5bf84 < _0x3f612d.length; _0xb5bf84++) {
> >             _0x485bac += _0x3f612d[_0xb5bf84];
> >         }
> >         return hex_md5(_0x485bac);
> >     }
> >     return { 'verifyParam': _0x6d646b };
> > });
> > (function (_0x266bf7, _0xec214d, _0x432101) {
> >     var _0x58e0f3 = function () {
> >         var _0x815ad2 = true;
> >         return function (_0x3b7d6e, _0x262cdc) {
> >             var _0x23544f = _0x815ad2 ? function () {
> >                 if (_0x262cdc) {
> >                     var _0x51827b = _0x262cdc.apply(_0x3b7d6e, arguments);
> >                     _0x262cdc = null;
> >                     return _0x51827b;
> >                 }
> >             } : function () {
> >             };
> >             _0x815ad2 = false;
> >             return _0x23544f;
> >         };
> >     }();
> >     (function () {
> >         _0x58e0f3(this, function () {
> >             var _0x415f58 = new RegExp('function *\\( *\\)');
> >             var _0xcae670 = new RegExp('\\+\\+ *(?:_0x(?:[a-f0-9]){4,6}|(?:\\b|\\d)[a-z0-9]{1,4}(?:\\b|\\d))', 'i');
> >             var _0x214a1a = _0x2771d2('init');
> >             if (!_0x415f58.test(_0x214a1a + 'chain') || !_0xcae670.test(_0x214a1a + 'input')) {
> >                 _0x214a1a('0');
> >             } else {
> >                 _0x2771d2();
> >             }
> >         })();
> >     }());
> >     var _0x1b0c4d = function () {
> >         var _0xccfaed = true;
> >         return function (_0x2ca1cb, _0x3c5b69) {
> >             var _0x46164b = _0xccfaed ? function () {
> >                 if (_0x3c5b69) {
> >                     var _0x378433 = _0x3c5b69.apply(_0x2ca1cb, arguments);
> >                     _0x3c5b69 = null;
> >                     return _0x378433;
> >                 }
> >             } : function () {
> >             };
> >             _0xccfaed = false;
> >             return _0x46164b;
> >         };
> >     }();
> >     var _0x3e9443 = _0x1b0c4d(this, function () {
> >         var _0x6215e8 = function () {
> >         };
> >         var _0x8ae592 = typeof window !== 'undefined' ? window : typeof process === 'object' && typeof require === 'function' && typeof global === 'object' ? global : this;
> >         if (!_0x8ae592.console) {
> >             _0x8ae592.console = function (_0x2251ea) {
> >                 var _0x432101 = {};
> >                 _0x432101.log = _0x2251ea;
> >                 _0x432101.warn = _0x2251ea;
> >                 _0x432101.debug = _0x2251ea;
> >                 _0x432101.info = _0x2251ea;
> >                 _0x432101.error = _0x2251ea;
> >                 _0x432101.exception = _0x2251ea;
> >                 _0x432101.trace = _0x2251ea;
> >                 return _0x432101;
> >             }(_0x6215e8);
> >         } else {
> >             _0x8ae592.console.log = _0x6215e8;
> >             _0x8ae592.console.warn = _0x6215e8;
> >             _0x8ae592.console.debug = _0x6215e8;
> >             _0x8ae592.console.info = _0x6215e8;
> >             _0x8ae592.console.error = _0x6215e8;
> >             _0x8ae592.console.exception = _0x6215e8;
> >             _0x8ae592.console.trace = _0x6215e8;
> >         }
> >     });
> >     _0x3e9443();
> > }(window));
> > function _0x2771d2(_0x5f4b85) {
> >     function _0x3a0add(_0x4dee5b) {
> >         {
> >             if (('' + _0x4dee5b / _0x4dee5b).length !== 1 || _0x4dee5b % 20 === 0) {
> >                 debugger;
> >             } else {
> >                 debugger;
> >             }
> >         }
> >         _0x3a0add(++_0x4dee5b);
> >     }
> >     try {
> >         if (_0x5f4b85) {
> >             return _0x3a0add;
> >         } else {
> >             _0x3a0add(0);
> >         }
> >     } catch (_0x1fbfd5) {
> >     }
> > }
> > setInterval(function () {
> >     _0x2771d2();
> > }, 4000);
> > encode_version = 'jsjiami.com.v5';
> > ```
> 
> 我就是用了你发的这个工具才得到结果的 一开始我找的工具效果差一点 真正有效的就是开头到 return { 'verifyParam': _0x6d646b };这一部分 其实你仔细看一下就发现跟我enc里的那些是完全对应的 我是在ChatGPT还原的基础上改出来的

感谢，我成了哈哈哈
![image](https://github.com/WangJerry1229/XXT_Library_Auto/assets/25475909/86ff0918-82ec-4be4-bbb0-e778cc6e3e66)

**Comment by Doone-skser** [comment]
> 我也没系统学过 抓包电脑端就是fiddler 手机端用的小黄鸟 enc这个基本是完全靠分析js得到的 也是看了之前另外一个issues里的提示用ChatGPT帮助还原了一下

电脑端用F12就可以了，不需要用fiddler那么麻烦。
