### ISSUE TITLE
学习通似乎上线了检测

### ISSUE THREAD

**Issue by wanfanggreat** [WangJerry1229/XXT_Library_Auto#9]
![IMG_20230712_162323.jpg](https://github.com/WangJerry1229/XXT_Library_Auto/assets/74281246/fe5eafaf-7234-475e-815f-c742fc8f4b20)

**Comment by MeiXiaoKe1212** [comment]
我也遇到了，不知道他们是检测了什么

**Comment by wanfanggreat** [comment]
> 我也遇到了，不知道他们是检测了什么

似乎是预约间隔，我尝试只预约一次，暂时没有弹出警告

**Comment by Miraitowa918** [comment]
我这都是用脚本的，我执行速度1秒多一点都抢不过，兄弟们有没有啥提升速度的办法

**Comment by MeiXiaoKe1212** [comment]
> 

提前十秒登录好，再提前2秒钟发送那个submit请求，我基本上都是0.2秒左右抢到

**Comment by MeiXiaoKe1212** [comment]
> 我这都是用脚本的，我执行速度1秒多一点都抢不过，兄弟们有没有啥提升速度的办法

提前几秒走完submit前的所有请求，再提前2秒钟循环发送那个submit请求，我基本上都是0.2秒左右抢到

**Comment by MeiXiaoKe1212** [comment]
> > 我也遇到了，不知道他们是检测了什么
> 
> 似乎是预约间隔，我尝试只预约一次，暂时没有弹出警告

收到警告了吗？你说的预约间隔是多次预约的间隔还是一次预约的间隔时间

**Comment by jeremisty99** [comment]
这么神奇吗 我最近没怎么关注 有研究的同学可以分享一下

**Comment by wanfanggreat** [comment]
> > > 我也遇到了，不知道他们是检测了什么
> > 
> > 似乎是预约间隔，我尝试只预约一次，暂时没有弹出警告
> 
> 收到警告了吗？你说的预约间隔是多次预约的间隔还是一次预约的间隔时间

我认为是一次预约完成后，下一次预约的时间间隔。
我在7月12号中午连续预约了4次，当天下午收到了50条提醒。第二天只预约1次，没有收到提醒。

**Comment by Miraitowa918** [comment]
> > > > 我也遇到了，不知道他们是检测了什么
> > > 
> > > 
> > > 似乎是预约间隔，我尝试只预约一次，暂时没有弹出警告
> > 
> > 
> > 收到警告了吗？你说的预约间隔是多次预约的间隔还是一次预约的间隔时间
> 
> 我认为是一次预约完成后，下一次预约的时间间隔。 我在7月12号中午连续预约了4次，当天下午收到了50条提醒。第二天只预约1次，没有收到提醒。

我今天也受到了警告，学校也在群里发通知说 运用大数据检测筛选使用脚本预约的行为，说是继续使用会自动拉黑 禁用预约功能，你们还有没有继续使用？

**Comment by jeremisty99** [comment]
> > > > > 我也遇到了，不知道他们是检测了什么
> > > > 
> > > > 
> > > > 似乎是预约间隔，我尝试只预约一次，暂时没有弹出警告
> > > 
> > > 
> > > 收到警告了吗？你说的预约间隔是多次预约的间隔还是一次预约的间隔时间
> > 
> > 
> > 我认为是一次预约完成后，下一次预约的时间间隔。 我在7月12号中午连续预约了4次，当天下午收到了50条提醒。第二天只预约1次，没有收到提醒。
> 
> 我今天也受到了警告，学校也在群里发通知说 运用大数据检测筛选使用脚本预约的行为，说是继续使用会自动拉黑 禁用预约功能，你们还有没有继续使用？

有没有更详细的检测规则 确实不太清楚是依据什么进行的判断 暂时没法解决
